### ISSUE TITLE
Default state for unhandledPromptBehavior should be "Dismiss and Notify"

### ISSUE THREAD

**Issue by whimboo** [w3c/webdriver#1276]
This issue has been caught by @andreastt while reviewing my patch on https://bugzilla.mozilla.org/show_bug.cgi?id=1264259. 

In the patch which enables the prompt behavior support in Firefox  I used "Dismiss and Notify" as default state because that is what I thought should be used if the `unhandledPromptBehavior` capability hasn't been specified for the `New Session` command.

Then here is what the spec lists when handling such an unexpected alert:

```
* missing value default state
* not in the table of simple dialogs
      - Dismiss the current user prompt.
      - Return an annotated unexpected alert open error. 
```

There is the `missing value default state` used, and no-where is a mention that `New Session` should set a valid default state. Benefit for that would be that this command could also return the actual mode in the active capabilities, so that clients are informed about the behavior in use.

**Comment by andreastt** [comment]
I think we should change the default value of the `unhandledPromptBehavior` capability to `dismiss and notify`, which is effectively what null evaluates to through the handler’s treatment of the missing value default state today.

Then we should remove the `missing value default state` and `not in the table of simple dialogs` branches of [handle any user prompts](https://w3c.github.io/webdriver/#dfn-handle-any-user-prompts).

This would make the capability behave like other similar capabilities such as `pageLoadStrategy`, where the matched/negotiated value is returned when the session is created.

**Comment by deckcha** [comment]
how to fix this issues 
1532077768082	geckodriver	INFO	geckodriver 0.21.0
1532077768090	geckodriver	INFO	Listening on 127.0.0.1:27207
1532077768755	mozrunner::runner	INFO	Running command: "C:\\Program Files\\Mozilla Firefox\\firefox.exe" "-marionette" "-foreground" "-no-remote" "-profile" "C:\\Users\\Tannay\\AppData\\Local\\Temp\\rust_mozprofile.LhR0ZEYDdMlf"
[GFX1]: Potential driver version mismatch ignored due to missing DLLs 0.0.0.0 and 0.0.0.0
1532077770384	Marionette	INFO	Listening on port 2828
[GFX1]: Potential driver version mismatch ignored due to missing DLLs 0.0.0.0 and 0.0.0.0
Exception in thread "main" org.openqa.selenium.WebDriverException: Process unexpectedly closed with status 0
Build info: version: '3.12.0', revision: '7c6e0b3', time: '2018-05-08T15:15:03.216Z'
System info: host: 'DESKTOP-40OK0AG', ip: '192.168.1.23', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '10.0.1'
Driver info: driver.version: FirefoxDriver
remote stacktrace: 
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:488)
	at org.openqa.selenium.remote.W3CHandshakeResponse.lambda$new$0(W3CHandshakeResponse.java:57)
	at org.openqa.selenium.remote.W3CHandshakeResponse.lambda$getResponseFunction$2(W3CHandshakeResponse.java:104)
	at org.openqa.selenium.remote.ProtocolHandshake.lambda$createSession$0(ProtocolHandshake.java:123)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:958)
	at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:127)
	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:502)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:488)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:543)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:126)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:73)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:136)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:543)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:207)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:130)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:125)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:103)
	at pack.FaceBook.main(FaceBook.java:14)
